name: 'ci_cd_project'
version: '1.0.0'
config-version: 2
require-dbt-version: [">=1.8.0", "<2.0.0"]

profile: 'workshop_duckdb'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
packages-install-path: "dbt_packages"

clean-targets:
  - "target"
  - "dbt_packages"

vars:
  schema_id: "local"

quoting:
  database: false
  schema: false
  identifier: false

models:
  ci_cd_project:
    +materialized: table
    +schema: "analytics"

  dbt_project_evaluator:
    +enabled: "{{ env_var('ENABLE_DBT_PROJECT_EVALUATOR', 'false') | lower == 'true' | as_bool }}"

data_tests:
  dbt_project_evaluator:
    +severity: "{{ env_var('DBT_PROJECT_EVALUATOR_SEVERITY', 'warn') }}"

seeds:
  +quote_columns: false
  dbt_project_evaluator:
    +enabled: "{{ env_var('ENABLE_DBT_PROJECT_EVALUATOR', 'false') | lower == 'true' | as_bool }}"
