workshop_duckdb:
  target: dev
  outputs:

    dev:
      type: duckdb
      path: "{{ env_var('DBT_DUCKDB_PATH', './warehouse/dev.duckdb') }}"
      schema: "{{ var('schema_id', 'analytics_dev') }}"
      threads: 4
      extensions: [httpfs]
      external_root: ./external

    pr:
      type: duckdb
      path: "./warehouse/pr_{{ var('schema_id','local') }}.duckdb"
      schema: "analytics_pr"
      threads: 4
      extensions: [httpfs]
      external_root: ./external
      attach:
        - path: ./warehouse/prod.duckdb
          alias: prod

    prod:
      type: duckdb
      path: "{{ env_var('DBT_DUCKDB_PATH', './warehouse/prod.duckdb') }}"
      schema: analytics
      threads: 8
      extensions: [httpfs]
      external_root: ./external
