name: dbt CD (DuckDB)

on:
  push:
    branches: ["main"]

jobs:
  cd:
    runs-on: ubuntu-latest
    env:
      DBT_PROFILES_DIR: .

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dbt-duckdb
        run: |
          python -m pip install --upgrade pip
          pip install -r dbt-requirements.txt

      - name: Ensure warehouse + empty DB
        run: |
          mkdir -p warehouse external
          python -c "import os,duckdb; os.makedirs('warehouse',exist_ok=True); duckdb.connect('warehouse/prod.duckdb').close()"

      - name: Build (full)
        run: dbt build --target prod

      - name: Upload manifest
        uses: actions/upload-artifact@v4
        with:
          name: dbt-manifest
          path: ./target/manifest.json
          retention-days: 7

      - name: Upload prod.duckdb
        uses: actions/upload-artifact@v4
        with:
          name: duckdb-prod-db
          path: warehouse/prod.duckdb
          retention-days: 7
