name: dbt CI (DuckDB)

on:
  pull_request:
    branches: ["main"]

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      # dbt finner profiles.yml i repoet
      DBT_PROFILES_DIR: .
      # Én DuckDB-fil per PR/commit (isolert miljø)
      DBT_DUCKDB_PATH: warehouse/pr_${{ github.event.pull_request.number }}__${{ github.sha }}.duckdb

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dbt + deps
        run: |
          python -m pip install --upgrade pip
          pip install -r dbt-requirements.txt

      - name: Ensure folders
        run: mkdir -p warehouse external state

      # (Valgfritt) Hent siste prod.duckdb for lesing/defer (hvis du ønsker "prod"-artefakter tilgjengelig)
      - name: Download latest prod.duckdb artifact (if any)
        shell: bash
        run: |
          set -euo pipefail
          curl -s -H "Authorization: Bearer ${{ github.token }}" \
            "https://api.github.com/repos/${{ github.repository }}/actions/artifacts?per_page=100" \
            -o artifacts.json
          prod_id=$(jq -r '.artifacts
            | map(select(.name=="duckdb-prod-db" and .expired==false))
            | sort_by(.created_at)
            | last
            | .id // empty' artifacts.json)
          if [[ -n "$prod_id" ]]; then
            curl -sL -H "Authorization: Bearer ${{ github.token }}" \
              "https://api.github.com/repos/${{ github.repository }}/actions/artifacts/$prod_id/zip" \
              -o prod.zip
            unzip -q prod.zip -d _prod || true
            # Flytt første .duckdb vi finner til warehouse/prod.duckdb
            f=$(ls -1 _prod/**.duckdb 2>/dev/null | head -n1 || true)
            if [[ -n "${f:-}" ]]; then
              mv "$f" warehouse/prod.duckdb
            fi
          fi

      # Last ned forrige manifest for Slim CI
      - name: Download latest manifest (if any)
        shell: bash
        run: |
          set -euo pipefail
          curl -s -H "Authorization: Bearer ${{ github.token }}" \
            "https://api.github.com/repos/${{ github.repository }}/actions/artifacts?per_page=100" \
            -o artifacts.json
          man_id=$(jq -r '.artifacts
            | map(select(.name=="dbt-manifest" and .expired==false))
            | sort_by(.created_at)
            | last
            | .id // empty' artifacts.json)
          if [[ -n "$man_id" ]]; then
            curl -sL -H "Authorization: Bearer ${{ github.token }}" \
              "https://api.github.com/repos/${{ github.repository }}/actions/artifacts/$man_id/zip" \
              -o manifest.zip
            unzip -q manifest.zip -d state || true
            # dbt forventer at --state peker til en mappe med manifest.json
            test -f state/manifest.json && cp state/manifest.json ./manifest.json || true
          fi

      - name: Generate schema ID (for per-PR schema hvis ønskelig)
        run: echo "SCHEMA_ID=pr_${{ github.event.pull_request.number }}__${{ github.sha }}" >> $GITHUB_ENV

      - name: dbt deps & seed
        run: |
          dbt deps
          dbt seed --target pr

      - name: Run dbt build (Slim CI if state present)
        run: |
          if [ -f "./manifest.json" ]; then
            dbt build -s 'state:modified+' --defer --state ./ --target pr --vars "schema_id: $SCHEMA_ID"
          else
            dbt build --target pr --vars "schema_id: $SCHEMA_ID"
          fi

      - name: Upload target/ for debugging
        uses: actions/upload-artifact@v4
        with:
          name: dbt-target
          path: target
          retention-days: 7

      - name: Upload PR DuckDB file
        uses: actions/upload-artifact@v4
        with:
          name: duckdb-pr-db
          path: ${{ env.DBT_DUCKDB_PATH }}
          retention-days: 7

      - name: Cleanup temp files
        run: rm -rf state/ _prod/ prod.zip manifest.zip artifacts.json || true
